#!/usr/bin/env sh

 "/usr/bin/falco",
 "-K",
 "/var/run/secrets/kubernetes.io/serviceaccount/token",
 "-k", "https://kubernetes.default",
 "-pk",
 "-o", "json_output=true",
 "-o", "program_output.enabled=true",
 "-o",  "program_output.program=jq '{text: .output}'
 | curl -d @- -X POST https://hooks.slack.com/services/see_your_slack_team/apps_settings_for/a_webhook_url"]
