#!/usr/bin/env sh

falco -d -o json_output=true \
  -o program_output.enabled=true \
  -o program_output.program=jq '{text: .output}' \
 | curl -d @- -X POST https://hooks.slack.com/services/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
