#!/usr/bin/env sh

mkdir -p /etc/falco
cp falco/*.yaml /etc/falco
cd /etc/falco

touch /var/log/falco_events.log
apt-get install linux-headers-$(uname -r)
lsmod | grep falco

docker run -d --name falco --privileged \
  -v /var/run/docker.sock:/host/var/run/docker.sock \
  -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro \
  -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro \
  -v /etc/falco/falco_rules.yaml:/etc/falco/falco_rules.yaml \
  -v /etc/falco/falco.yaml:/etc/falco/falco.yaml \
  -v /var/log/falco_events.log:/var/log/falco_events.log \
  sysdig/falco \
  falco
