#!/usr/bin/env sh

docker run -i -t -v /var/run/docker.sock:/host/var/run/docker.sock \
  -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro \
  -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro \
  sysdig/falco \
  falco -d -o json_output=true \
    -o program_output.enabled=true \
    -o program_output.program=jq '{text: .output}' \
   | curl -d @- -X POST https://hooks.slack.com/services/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
  
